using BetStrategy.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;

namespace BetStrategy.ViewModels
{
    public class TestViewModel : BaseViewModel
    {
        private PreferResultToStringConverter converter = new PreferResultToStringConverter();

        private ObservableCollection<Recommend> _recommends = null;
        public ObservableCollection<Recommend> Recommends
        {
            get
            {
                return _recommends;
            }
        }

        private ObservableCollection<Person> _topPerson = null;
        public ObservableCollection<Person> TopPerson
        {
            get
            {
                return _topPerson;
            }
        }

        private ObservableCollection<YieldRoiPerson> _topYieldRoiPerson = null;
        public ObservableCollection<YieldRoiPerson> TopYieldRoiPerson
        {
            get
            {
                return _topYieldRoiPerson;
            }
        }

        public TestViewModel()
        {
            InitRecommends();
            InitTopPerson();
            InitTopYieldRoiPerson();
        }

        private void InitRecommends()
        {
            _recommends = new ObservableCollection<Recommend>();
            _recommends.Add(new Recommend() { Time1 = "05-01 07:15", Host = new Team() { TeamName = "堤格雷" }, OddStake = new OddStake() { Description = "2/2.5球" }, Guest = new Team() { TeamName = "奧林匹亞" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.940f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 23:03", Person = new Person() { Name = "bin-bin" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:00", Host = new Team() { TeamName = "喜百年U20" }, OddStake = new OddStake() { Description = "球半/两球" }, Guest = new Team() { TeamName = "登地U20" }, Prefer = new Prefer() { Description = "喜百年U20" }, Odds = 0.920f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 23:02", Person = new Person() { Name = "回心融雪衣" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾恩" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "艾斯迪格拿" }, Prefer = new Prefer() { Description = "艾斯迪格拿" }, Odds = 0.860f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 23:01", Person = new Person() { Name = "不学无术" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "車斯曼" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "赫默爾亨普斯特德城" }, Prefer = new Prefer() { Description = "赫默爾亨普斯特德城" }, Odds = 0.800f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:57", Person = new Person() { Name = "sos73" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 07:15", Host = new Team() { TeamName = "堤格雷" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "奧林匹亞" }, Prefer = new Prefer() { Description = "奧林匹亞" }, Odds = 1.020f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:56", Person = new Person() { Name = "茶居" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "米禾爾" }, OddStake = new OddStake() { Description = "平手" }, Guest = new Team() { TeamName = "水晶宮" }, Prefer = new Prefer() { Description = "水晶宮" }, Odds = 0.800f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:56", Person = new Person() { Name = "运达不来霉" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "菲爾德" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "盧沙奧林" }, Prefer = new Prefer() { Description = "菲爾德" }, Odds = 1.020f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:56", Person = new Person() { Name = "mzzzzzzm" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球/球半" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "多特蒙德" }, Odds = 0.890f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:55", Person = new Person() { Name = "西班牙王子" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 01:30", Host = new Team() { TeamName = "馬摩洛迪落日" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "自由州星" }, Prefer = new Prefer() { Description = "馬摩洛迪落日" }, Odds = 0.970f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:54", Person = new Person() { Name = "大D哥" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:45", Host = new Team() { TeamName = "阿爾艾利開羅" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "索莫哈" }, Prefer = new Prefer() { Description = "索莫哈" }, Odds = 0.840f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:49", Person = new Person() { Name = "凤凰谷" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "伊斯特雷格" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "多佛" }, Prefer = new Prefer() { Description = "多佛" }, Odds = 0.800f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:49", Person = new Person() { Name = "sweetcat" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球/球半" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "多特蒙德" }, Odds = 0.890f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:49", Person = new Person() { Name = "雪儿" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "切爾弗德" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "塞利斯貝瑞" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.800f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:44", Person = new Person() { Name = "春游记" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球/球半" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "多特蒙德" }, Odds = 0.880f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:42", Person = new Person() { Name = "jaddeking" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 01:30", Host = new Team() { TeamName = "馬摩洛迪落日" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "自由州星" }, Prefer = new Prefer() { Description = "自由州星" }, Odds = 0.850f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:41", Person = new Person() { Name = "爷有旺仔" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 01:30", Host = new Team() { TeamName = "馬摩洛迪落日" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "自由州星" }, Prefer = new Prefer() { Description = "馬摩洛迪落日" }, Odds = 0.970f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:28", Person = new Person() { Name = "重在参与" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾恩" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "艾斯迪格拿" }, Prefer = new Prefer() { Description = "艾斯迪格拿" }, Odds = 0.900f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:19", Person = new Person() { Name = "爽爽" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "艾青洽" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "巴克利城" }, Prefer = new Prefer() { Description = "巴克利城" }, Odds = 0.900f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:15", Person = new Person() { Name = "提子味" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾恩" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "艾斯迪格拿" }, Prefer = new Prefer() { Description = "艾斯迪格拿" }, Odds = 0.900f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:13", Person = new Person() { Name = "一天一点赢" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:00", Host = new Team() { TeamName = "普拉騰斯" }, OddStake = new OddStake() { Description = "2/2.5球" }, Guest = new Team() { TeamName = "瑪倫" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.880f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:12", Person = new Person() { Name = "天巧星燕青" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球/球半" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 1.050f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:11", Person = new Person() { Name = "不孕不育专家" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "菲爾德" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "盧沙奧林" }, Prefer = new Prefer() { Description = "盧沙奧林" }, Odds = 0.850f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:08", Person = new Person() { Name = "章鱼帝" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾恩" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "艾斯迪格拿" }, Prefer = new Prefer() { Description = "艾恩" }, Odds = 0.960f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:07", Person = new Person() { Name = "杀出个黎明" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球/球半" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 1.060f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 22:00", Person = new Person() { Name = "海里昙花" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "車斯曼" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "赫默爾亨普斯特德城" }, Prefer = new Prefer() { Description = "赫默爾亨普斯特德城" }, Odds = 0.800f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:58", Person = new Person() { Name = "十万火急" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:59", Host = new Team() { TeamName = "沃爾夫斯堡青年隊" }, OddStake = new OddStake() { Description = "2.5球" }, Guest = new Team() { TeamName = "雲達不萊梅青年隊" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.970f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:56", Person = new Person() { Name = "飞天神猪" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球/球半" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "多特蒙德" }, Odds = 0.860f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:55", Person = new Person() { Name = "zx01668" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:00", Host = new Team() { TeamName = "普拉騰斯" }, OddStake = new OddStake() { Description = "2/2.5球" }, Guest = new Team() { TeamName = "瑪倫" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.800f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:54", Person = new Person() { Name = "浪人心声" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾恩" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "艾斯迪格拿" }, Prefer = new Prefer() { Description = "艾斯迪格拿" }, Odds = 0.980f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:50", Person = new Person() { Name = "余韵犹在" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "3.5球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.830f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:46", Person = new Person() { Name = "小花" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "多特蒙德" }, Odds = 0.980f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:42", Person = new Person() { Name = "弹弓六" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "多特蒙德" }, Odds = 0.980f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:34", Person = new Person() { Name = "慢慢来" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾恩" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "艾斯迪格拿" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.960f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:33", Person = new Person() { Name = "八月十日" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:59", Host = new Team() { TeamName = "沙巴罕" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "阿爾葛拉法" }, Prefer = new Prefer() { Description = "阿爾葛拉法" }, Odds = 1.020f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:30", Person = new Person() { Name = "童年" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "3.5球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.830f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:20", Person = new Person() { Name = "人在美洲" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "BW林茲" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "卡芬堡" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.870f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:16", Person = new Person() { Name = "足球冠军" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "聖普爾頓" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "亞塔奇" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.890f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:14", Person = new Person() { Name = "无冕之王" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 0.930f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:11", Person = new Person() { Name = "木棉树" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 07:15", Host = new Team() { TeamName = "堤格雷" }, OddStake = new OddStake() { Description = "2/2.5球" }, Guest = new Team() { TeamName = "奧林匹亞" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.840f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:08", Person = new Person() { Name = "龙8啤酒" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "3.5球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.830f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 21:06", Person = new Person() { Name = "黑客的态度" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾恩" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "艾斯迪格拿" }, Prefer = new Prefer() { Description = "艾斯迪格拿" }, Odds = 0.980f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:58", Person = new Person() { Name = "我行我素" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 09:30", Host = new Team() { TeamName = "提華納" }, OddStake = new OddStake() { Description = "半/一" }, Guest = new Team() { TeamName = "彭美拉斯" }, Prefer = new Prefer() { Description = "提華納" }, Odds = 0.910f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:52", Person = new Person() { Name = "斌少" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 0.930f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:52", Person = new Person() { Name = "cxm383" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "3.5球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.830f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:50", Person = new Person() { Name = "神一样的玩家" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:59", Host = new Team() { TeamName = "沙巴罕" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "阿爾葛拉法" }, Prefer = new Prefer() { Description = "小球" }, Odds = 1.010f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:43", Person = new Person() { Name = "乌龙波" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 07:15", Host = new Team() { TeamName = "堤格雷" }, OddStake = new OddStake() { Description = "2/2.5球" }, Guest = new Team() { TeamName = "奧林匹亞" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.840f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:39", Person = new Person() { Name = "钱龙大帝" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "BW林茲" }, OddStake = new OddStake() { Description = "受半球" }, Guest = new Team() { TeamName = "卡芬堡" }, Prefer = new Prefer() { Description = "卡芬堡" }, Odds = 0.900f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:37", Person = new Person() { Name = "辉煌先锋" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "多特蒙德" }, Odds = 0.980f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:37", Person = new Person() { Name = "segespa" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾爾雷恩" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "希拉爾" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.850f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:36", Person = new Person() { Name = "yuelao200" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾恩" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "艾斯迪格拿" }, Prefer = new Prefer() { Description = "艾斯迪格拿" }, Odds = 0.980f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:25", Person = new Person() { Name = "神算子" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "BW林茲" }, OddStake = new OddStake() { Description = "受半球" }, Guest = new Team() { TeamName = "卡芬堡" }, Prefer = new Prefer() { Description = "卡芬堡" }, Odds = 0.900f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 20:00", Person = new Person() { Name = "瑪莉皇后2號郵輪" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:50", Host = new Team() { TeamName = "艾恩" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "艾斯迪格拿" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.900f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:26", Person = new Person() { Name = "红日" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "哈特堡格" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "路斯登洛" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.900f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:24", Person = new Person() { Name = "彩世界花园" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "3.5球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.830f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:20", Person = new Person() { Name = "大头" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "多特蒙德" }, Odds = 0.980f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:19", Person = new Person() { Name = "xytlove" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "SV格羅迪格" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "第一維也納" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.880f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:19", Person = new Person() { Name = "独角刺龙" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 0.930f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:18", Person = new Person() { Name = "苦楝鸟" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:59", Host = new Team() { TeamName = "沙巴罕" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "阿爾葛拉法" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.850f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:16", Person = new Person() { Name = "飞天戟" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:00", Host = new Team() { TeamName = "阿爾艾利吉達(中)" }, OddStake = new OddStake() { Description = "球半" }, Guest = new Team() { TeamName = "納薩SC" }, Prefer = new Prefer() { Description = "阿爾艾利吉達(中)" }, Odds = 0.880f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:13", Person = new Person() { Name = "中奖" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "印戈斯塔德青年隊" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "拜仁慕尼黑青年隊" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.860f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:10", Person = new Person() { Name = "香鸡脚" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "哈特堡格" }, OddStake = new OddStake() { Description = "平/半" }, Guest = new Team() { TeamName = "路斯登洛" }, Prefer = new Prefer() { Description = "路斯登洛" }, Odds = 0.940f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:04", Person = new Person() { Name = "为梦等你" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "BW林茲" }, OddStake = new OddStake() { Description = "受半球" }, Guest = new Team() { TeamName = "卡芬堡" }, Prefer = new Prefer() { Description = "卡芬堡" }, Odds = 0.900f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 19:03", Person = new Person() { Name = "北风呼啸" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 07:15", Host = new Team() { TeamName = "堤格雷" }, OddStake = new OddStake() { Description = "2/2.5球" }, Guest = new Team() { TeamName = "奧林匹亞" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.840f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 18:39", Person = new Person() { Name = "一场成名" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 0.930f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 18:32", Person = new Person() { Name = "冷云" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "中央海岸" }, OddStake = new OddStake() { Description = "2.5球" }, Guest = new Team() { TeamName = "柏雷素爾" }, Prefer = new Prefer() { Description = "大球" }, Odds = 1.060f, Result = "0-3", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 18:20", Person = new Person() { Name = "东北球王" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "3.5球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "大球" }, Odds = 1.060f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 18:13", Person = new Person() { Name = "森林" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "貴州人和" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "水原三星" }, Prefer = new Prefer() { Description = "水原三星" }, Odds = 0.940f, Result = "2-2", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 18:12", Person = new Person() { Name = "纽约红牛" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "中央海岸" }, OddStake = new OddStake() { Description = "半/一" }, Guest = new Team() { TeamName = "柏雷素爾" }, Prefer = new Prefer() { Description = "中央海岸" }, Odds = 0.940f, Result = "0-3", PreferResult = (PreferResult)converter.ConvertBack("输盘", typeof(PreferResult), null, null), Time2 = "04-30 18:12", Person = new Person() { Name = "0度心凉" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "3.5球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.830f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 18:08", Person = new Person() { Name = "lili369" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "中央海岸" }, OddStake = new OddStake() { Description = "2.5球" }, Guest = new Team() { TeamName = "柏雷素爾" }, Prefer = new Prefer() { Description = "大球" }, Odds = 1.060f, Result = "0-3", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 18:04", Person = new Person() { Name = "身不由己" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "貴州人和" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "水原三星" }, Prefer = new Prefer() { Description = "水原三星" }, Odds = 0.940f, Result = "2-2", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 17:49", Person = new Person() { Name = "asd3388" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "廣島三箭" }, OddStake = new OddStake() { Description = "平手" }, Guest = new Team() { TeamName = "北京國安" }, Prefer = new Prefer() { Description = "北京國安" }, Odds = 0.900f, Result = "0-0", PreferResult = (PreferResult)converter.ConvertBack("走水", typeof(PreferResult), null, null), Time2 = "04-30 17:49", Person = new Person() { Name = "歡樂今宵" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "浦項制鐵" }, OddStake = new OddStake() { Description = "半/一" }, Guest = new Team() { TeamName = "賓約哥" }, Prefer = new Prefer() { Description = "賓約哥" }, Odds = 0.820f, Result = "1-1", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 17:49", Person = new Person() { Name = "帅的躲家里" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "廣島三箭" }, OddStake = new OddStake() { Description = "平手" }, Guest = new Team() { TeamName = "北京國安" }, Prefer = new Prefer() { Description = "北京國安" }, Odds = 0.900f, Result = "0-0", PreferResult = (PreferResult)converter.ConvertBack("走水", typeof(PreferResult), null, null), Time2 = "04-30 17:46", Person = new Person() { Name = "雪儿" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 0.930f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 17:43", Person = new Person() { Name = "跳舞草" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "浦項制鐵" }, OddStake = new OddStake() { Description = "半/一" }, Guest = new Team() { TeamName = "賓約哥" }, Prefer = new Prefer() { Description = "賓約哥" }, Odds = 0.820f, Result = "1-1", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 17:43", Person = new Person() { Name = "轻轻巧巧" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 0.930f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 17:42", Person = new Person() { Name = "东航空乘" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "貴州人和" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "水原三星" }, Prefer = new Prefer() { Description = "水原三星" }, Odds = 0.940f, Result = "2-2", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 17:41", Person = new Person() { Name = "霸王龙" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "中央海岸" }, OddStake = new OddStake() { Description = "半/一" }, Guest = new Team() { TeamName = "柏雷素爾" }, Prefer = new Prefer() { Description = "柏雷素爾" }, Odds = 0.940f, Result = "0-3", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 17:41", Person = new Person() { Name = "LXF1234" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "廣島三箭" }, OddStake = new OddStake() { Description = "2球" }, Guest = new Team() { TeamName = "北京國安" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.900f, Result = "0-0", PreferResult = (PreferResult)converter.ConvertBack("输盘", typeof(PreferResult), null, null), Time2 = "04-30 17:39", Person = new Person() { Name = "笑妹" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "廣島三箭" }, OddStake = new OddStake() { Description = "平手" }, Guest = new Team() { TeamName = "北京國安" }, Prefer = new Prefer() { Description = "北京國安" }, Odds = 0.900f, Result = "0-0", PreferResult = (PreferResult)converter.ConvertBack("走水", typeof(PreferResult), null, null), Time2 = "04-30 17:33", Person = new Person() { Name = "一天一点赢" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:59", Host = new Team() { TeamName = "沙巴罕" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "阿爾葛拉法" }, Prefer = new Prefer() { Description = "沙巴罕" }, Odds = 0.860f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 17:32", Person = new Person() { Name = "iq" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "廣島三箭" }, OddStake = new OddStake() { Description = "平手" }, Guest = new Team() { TeamName = "北京國安" }, Prefer = new Prefer() { Description = "廣島三箭" }, Odds = 0.980f, Result = "0-0", PreferResult = (PreferResult)converter.ConvertBack("走水", typeof(PreferResult), null, null), Time2 = "04-30 17:31", Person = new Person() { Name = "lzzw0076" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "中央海岸" }, OddStake = new OddStake() { Description = "2.5球" }, Guest = new Team() { TeamName = "柏雷素爾" }, Prefer = new Prefer() { Description = "小球" }, Odds = 0.800f, Result = "0-3", PreferResult = (PreferResult)converter.ConvertBack("输盘", typeof(PreferResult), null, null), Time2 = "04-30 17:28", Person = new Person() { Name = "高原" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 0.930f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 17:20", Person = new Person() { Name = "老鬼看盘" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "貴州人和" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "水原三星" }, Prefer = new Prefer() { Description = "貴州人和" }, Odds = 0.940f, Result = "2-2", PreferResult = (PreferResult)converter.ConvertBack("输盘", typeof(PreferResult), null, null), Time2 = "04-30 17:18", Person = new Person() { Name = "默默非金" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "一球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "皇家馬德里" }, Odds = 0.930f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 16:57", Person = new Person() { Name = "罗纳尔多" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "貴州人和" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "水原三星" }, Prefer = new Prefer() { Description = "水原三星" }, Odds = 0.940f, Result = "2-2", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 16:54", Person = new Person() { Name = "贝多芬" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "浦項制鐵" }, OddStake = new OddStake() { Description = "2.5球" }, Guest = new Team() { TeamName = "賓約哥" }, Prefer = new Prefer() { Description = "大球" }, Odds = 1.060f, Result = "1-1", PreferResult = (PreferResult)converter.ConvertBack("输盘", typeof(PreferResult), null, null), Time2 = "04-30 16:53", Person = new Person() { Name = "朝鲜核武器" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 00:30", Host = new Team() { TeamName = "SV格羅迪格" }, OddStake = new OddStake() { Description = "2.5/3球" }, Guest = new Team() { TeamName = "第一維也納" }, Prefer = new Prefer() { Description = "大球" }, Odds = 0.880f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 16:51", Person = new Person() { Name = "墨斗红云" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "廣島三箭" }, OddStake = new OddStake() { Description = "平手" }, Guest = new Team() { TeamName = "北京國安" }, Prefer = new Prefer() { Description = "廣島三箭" }, Odds = 0.980f, Result = "0-0", PreferResult = (PreferResult)converter.ConvertBack("走水", typeof(PreferResult), null, null), Time2 = "04-30 16:37", Person = new Person() { Name = "阿麦的理想" } });
            _recommends.Add(new Recommend() { Time1 = "05-01 02:45", Host = new Team() { TeamName = "皇家馬德里" }, OddStake = new OddStake() { Description = "3.5球" }, Guest = new Team() { TeamName = "多特蒙德" }, Prefer = new Prefer() { Description = "大球" }, Odds = 1.060f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 16:35", Person = new Person() { Name = "谷雨" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "廣島三箭" }, OddStake = new OddStake() { Description = "平手" }, Guest = new Team() { TeamName = "北京國安" }, Prefer = new Prefer() { Description = "北京國安" }, Odds = 0.900f, Result = "0-0", PreferResult = (PreferResult)converter.ConvertBack("走水", typeof(PreferResult), null, null), Time2 = "04-30 16:28", Person = new Person() { Name = "星星点灯" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "貴州人和" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "水原三星" }, Prefer = new Prefer() { Description = "水原三星" }, Odds = 0.940f, Result = "2-2", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 16:26", Person = new Person() { Name = "wintion" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "浦項制鐵" }, OddStake = new OddStake() { Description = "半/一" }, Guest = new Team() { TeamName = "賓約哥" }, Prefer = new Prefer() { Description = "賓約哥" }, Odds = 0.820f, Result = "1-1", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 16:25", Person = new Person() { Name = "空山新雨" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "貴州人和" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "水原三星" }, Prefer = new Prefer() { Description = "貴州人和" }, Odds = 0.940f, Result = "2-2", PreferResult = (PreferResult)converter.ConvertBack("输盘", typeof(PreferResult), null, null), Time2 = "04-30 16:19", Person = new Person() { Name = "阿根廷" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:00", Host = new Team() { TeamName = "廣島三箭" }, OddStake = new OddStake() { Description = "平手" }, Guest = new Team() { TeamName = "北京國安" }, Prefer = new Prefer() { Description = "北京國安" }, Odds = 0.900f, Result = "0-0", PreferResult = (PreferResult)converter.ConvertBack("走水", typeof(PreferResult), null, null), Time2 = "04-30 16:16", Person = new Person() { Name = "西班牙王子" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 23:59", Host = new Team() { TeamName = "沙巴罕" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "阿爾葛拉法" }, Prefer = new Prefer() { Description = "沙巴罕" }, Odds = 0.860f, Result = "-", PreferResult = (PreferResult)converter.ConvertBack("等待", typeof(PreferResult), null, null), Time2 = "04-30 16:12", Person = new Person() { Name = "lijin" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "貴州人和" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "水原三星" }, Prefer = new Prefer() { Description = "貴州人和" }, Odds = 0.940f, Result = "2-2", PreferResult = (PreferResult)converter.ConvertBack("输盘", typeof(PreferResult), null, null), Time2 = "04-30 16:04", Person = new Person() { Name = "黄金一代" } });
            _recommends.Add(new Recommend() { Time1 = "04-30 18:30", Host = new Team() { TeamName = "貴州人和" }, OddStake = new OddStake() { Description = "半球" }, Guest = new Team() { TeamName = "水原三星" }, Prefer = new Prefer() { Description = "水原三星" }, Odds = 0.940f, Result = "2-2", PreferResult = (PreferResult)converter.ConvertBack("赢盘", typeof(PreferResult), null, null), Time2 = "04-30 15:59", Person = new Person() { Name = "庄家倒霉了" } });
        }

        private void InitTopPerson()
        {
            _topPerson = new ObservableCollection<Person>();
            _topPerson.Add(new Person() { Name = "无聊玩玩", Profit = 11.5f, Total = 25, Win = 14, WinHalf = 5, Lose = 5, LoseHalf = 0, Draw = 1 });
            _topPerson.Add(new Person() { Name = "多伦多猛龙", Profit = 11f, Total = 27, Win = 16, WinHalf = 3, Lose = 6, LoseHalf = 1, Draw = 1 });
            _topPerson.Add(new Person() { Name = "纽约火焰", Profit = 11f, Total = 24, Win = 14, WinHalf = 4, Lose = 5, LoseHalf = 0, Draw = 1 });
            _topPerson.Add(new Person() { Name = "财爷win888", Profit = 10.5f, Total = 28, Win = 18, WinHalf = 0, Lose = 7, LoseHalf = 1, Draw = 2 });
            _topPerson.Add(new Person() { Name = "重在参与", Profit = 10f, Total = 28, Win = 16, WinHalf = 2, Lose = 7, LoseHalf = 0, Draw = 3 });
            _topPerson.Add(new Person() { Name = "天巧星燕青", Profit = 10f, Total = 24, Win = 14, WinHalf = 4, Lose = 6, LoseHalf = 0, Draw = 0 });
            _topPerson.Add(new Person() { Name = "喜龙泪", Profit = 9f, Total = 26, Win = 11, WinHalf = 6, Lose = 4, LoseHalf = 2, Draw = 3 });
            _topPerson.Add(new Person() { Name = "重新来过", Profit = 9f, Total = 26, Win = 15, WinHalf = 2, Lose = 7, LoseHalf = 0, Draw = 2 });
            _topPerson.Add(new Person() { Name = "球王之王", Profit = 8.5f, Total = 29, Win = 15, WinHalf = 4, Lose = 8, LoseHalf = 1, Draw = 0 });
            _topPerson.Add(new Person() { Name = "剑岛", Profit = 8.5f, Total = 24, Win = 14, WinHalf = 3, Lose = 7, LoseHalf = 0, Draw = 0 });
            _topPerson.Add(new Person() { Name = "茶居", Profit = 8f, Total = 32, Win = 19, WinHalf = 0, Lose = 11, LoseHalf = 0, Draw = 2 });
            _topPerson.Add(new Person() { Name = "哥是杯清茶", Profit = 8f, Total = 28, Win = 16, WinHalf = 2, Lose = 8, LoseHalf = 2, Draw = 0 });
            _topPerson.Add(new Person() { Name = "足球擂台", Profit = 7.5f, Total = 29, Win = 16, WinHalf = 1, Lose = 7, LoseHalf = 4, Draw = 1 });
            _topPerson.Add(new Person() { Name = "余韵犹在", Profit = 7.5f, Total = 26, Win = 13, WinHalf = 3, Lose = 7, LoseHalf = 0, Draw = 3 });
            _topPerson.Add(new Person() { Name = "十万火急", Profit = 7.5f, Total = 23, Win = 14, WinHalf = 0, Lose = 6, LoseHalf = 1, Draw = 2 });
            _topPerson.Add(new Person() { Name = "凤凰谷", Profit = 7.5f, Total = 22, Win = 12, WinHalf = 3, Lose = 5, LoseHalf = 2, Draw = 0 });
            _topPerson.Add(new Person() { Name = "重在娱乐", Profit = 7f, Total = 28, Win = 15, WinHalf = 3, Lose = 9, LoseHalf = 1, Draw = 0 });
            _topPerson.Add(new Person() { Name = "红红火火", Profit = 7f, Total = 26, Win = 15, WinHalf = 2, Lose = 9, LoseHalf = 0, Draw = 0 });
            _topPerson.Add(new Person() { Name = "竹叶青", Profit = 6.5f, Total = 31, Win = 17, WinHalf = 1, Lose = 10, LoseHalf = 2, Draw = 1 });
            _topPerson.Add(new Person() { Name = "火車頭", Profit = 6.5f, Total = 26, Win = 13, WinHalf = 2, Lose = 7, LoseHalf = 1, Draw = 3 });
        }

        private void InitTopYieldRoiPerson()
        {
            _topYieldRoiPerson = new ObservableCollection<YieldRoiPerson>();
            foreach (var i in TopPersonProvider.Instance.PreferMost)
            {
                var p = new YieldRoiPerson(i);
                _topYieldRoiPerson.Add(p);
            }
        }
    }
}
